name: Deploy NestJS Lambda from S3

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: normal
  S3_BUCKET: ekemsss
  S3_KEY: function.zip

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Python (for AWS CLI)
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install AWS CLI
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Zip Lambda package
        run: |
          zip -r function.zip dist node_modules package.json -x "*.test.*" "*.spec.*" "*.env"

      - name: Upload ZIP to S3
        run: |
          aws s3 cp function.zip s3://${{ env.S3_BUCKET }}/${{ env.S3_KEY }}

      - name: Deploy Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --s3-key ${{ env.S3_KEY }}

