name: Deploy Lambda Function

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: normal
  AWS_ROLE_TO_ASSUME: arn:aws:iam::140023404662:role/normal-role-efqu9sk5

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActionsLambdaDeployment
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Zip Lambda package
        run: zip -r function.zip dist node_modules package.json

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://function.zip
